import type { Permission, UserRole } from './types'

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  admin: [
    'dashboard:view',
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'projects:view',
    'projects:create',
    'projects:update',
    'projects:delete',
    'requests:view',
    'requests:create',
    'requests:update',
    'requests:delete',
    'analytics:view',
    'settings:view',
    'settings:update',
    'ui-kit:view',
  ],
  manager: [
    'dashboard:view',
    'users:view',
    'users:create',
    'users:update',
    'projects:view',
    'projects:create',
    'projects:update',
    'requests:view',
    'requests:create',
    'requests:update',
    'analytics:view',
    'settings:view',
    'settings:update',
    'ui-kit:view',
  ],
  user: [
    'dashboard:view',
    'users:view',
    'projects:view',
    'requests:view',
    'requests:create',
    'analytics:view',
    'settings:view',
    'ui-kit:view',
  ],
  guest: ['ui-kit:view'],
}
